version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name:  app-php
        # restart: always
        tty: true
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - shopcart-network

    nginx-api:
        depends_on:
            - app
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: api-php
        # restart: always
        tty: true
        ports:
            - "8081:80"
        networks:
            - shopcart-network
    nginx-cliente:
        depends_on:
            - app
        build:
            context: ./car-rental-client-app/browser
            dockerfile: Dockerfile
        container_name: app-cliente
        tty: true
        ports:
            - "8082:80"
        networks:
            - shopcart-network
    database:
        image: mariadb
        container_name: database-shopcart
        # restart: always
        ports:
            - "3308:3306"
        volumes:
            - mysql-shopcart:/var/lib/mysql
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
        environment:
            MARIADB_DATABASE: shopcart
            MARIADB_USER: shopcart
            MARIADB_PASSWORD: shopcart
            MARIADB_ROOT_PASSWORD: root
        networks:
            - shopcart-network
volumes:
    mysql-shopcart:
networks:
    shopcart-network:
        driver: bridge
