version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name:  app-php
        # restart: always
        tty: true
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - shopcart-network

    nginx-api:
        depends_on:
            - app
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: api-php
        # restart: always
        tty: true
        ports:
            - "8081:80"
        networks:
            - shopcart-network
    nginx-cliente:
        depends_on:
            - app
        build:
            context: ./car-rental-client-app/browser
            dockerfile: Dockerfile
        container_name: app-cliente
        tty: true
        ports:
            - "8082:80"
        networks:
            - shopcart-network
    database:
        image: mysql
        container_name: database-shopcart
        restart: always
        ports:
            - "3308:3306"
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shopcart
            MYSQL_USER: shopcart
        networks:
            - shopcart-network
volumes:
    mysql:
networks:
  shopcart-network:
    driver: bridge
